### ISSUE TITLE
Missing code in https://github.com/jorgetite/grav-theme-qbee/blob/master/templates/partials/fragments/hero.html.twig

### ISSUE THREAD

**Issue by krismyu** [jorgetite/grav-theme-qboss#3]
Right now all that the https://github.com/jorgetite/grav-theme-qbee/blob/master/templates/partials/fragments/hero.html.twig file contains is:

`{% extends 'partials/fragments/default.html.twig' %}`

Is that all that is supposed to be in there? Would it be possible to have some sample code showing what a hero.md file should look like? Many thanks for developing this theme!

**Comment by jorgetite** [comment]
Yes, since hero.html.twig file is a template, that is all the content the file contains. 

If you want to create a hero page in your website you would have to create a new modular page (`modular.md`) that can host a hero modular view (`hero.md`). For example the main page of the demo site (http://qbee.jorgetite.com/) is a modular page under the user/pages/01.home folder that host a hero view and a features view. The folder structure looks like this:

```
|- 01.home
    |- 01._hero
       |- hero.md
    |- 02._features
       |- features.md
    |- modular.md
```

The content of `modular.md` is:

```
---
title: Home
body_classes: modular
show_header: true
show_footer: true
onpage_menu: false

content:
    items: @self.modular
---
```

hero.md:
```
---
title: 'QBee Theme'
subtitle: 'The lightweight and minimal HTML 5 theme for Grav flat-file CMS'
media_order: animal-bee-bloom.jpg
show_heading: false
color_scheme: scheme-light
padding: xl-pad
css_classes: text-center
css_styles: 'height: 640px;'
image: animal-bee-bloom.jpg
image_position: back
parallax_enabled: false
parallax_direction: vertical
parallax_factor: '0.5'
show_header: true
show_footer: true
---

<h1 class="title">QBee Theme</h1>

### The lightweight and minimal HTML 5 theme for Grav flat-file CMS

<br />
<br />
<a href="https://github.com/jorgetite/grav-theme-qbee/archive/master.zip" class="button large secondary" target="_blank"><i class="fas fa-download"></i> Download</a>

```

and features.md:
```
---
title: Features
subtitle: 'These are some of the things that make QBee a simple yet powerful theme for Grav'
show_heading: true
color_scheme: scheme-dark
padding: md-pad
image_position: none
parallax_enabled: false
parallax_direction: vertical
parallax_factor: '0.5'
columns: col-4
features:
    -
        icon: 'far fa-circle  fa-fw'
        header: 'Clean & Minimal'
        text: 'Using a strong sense of alignment between content and graphic elements, QBee creates a clean, simple and effective design.'
    -
        icon: 'fas fa-expand-arrows-alt  fa-fw'
        header: 'Flexible & Extensible'
        text: 'You can easily customize or modify QBee to meet your needs, from personal web-sites to large and complex websites.'
    -
        icon: 'fas fa-mobile-alt  fa-fw'
        header: Cross-browser
        text: 'QBee works in all modern browsers, both desktop and mobile, including latest Chrome, Firefox, Safari, Opera, IE and Edge.'
    -
        icon: 'fas fa-code  fa-fw'
        header: 'Kube Framework'
        text: 'Kube fully embraces latest and greatest tech, while relying on proven concepts.'
    -
        icon: 'fab fa-font-awesome-flag fa-fw'
        header: 'Font Awesome'
        text: 'QBee supports Font Awesome 5.1, the web’s most popular icon set and toolkit.'
    -
        icon: 'fas fa-users  fa-fw'
        header: 'Open Source'
        text: 'QBee Theme is absolutely free for personal or commercial use, licensed under MIT. '
show_header: true
show_footer: true
---

```

You can use the Admin Panel Plugin to generate the folder structure and the `*.md` files.
